buildo/retro

- .scalafmt.conf
- toctoc/scripts/db-start.sh
- toctoc/scripts/db-stop.sh
- toctoc/slickMySql/src/main/scala/io.buildo.toctoc/slick/authentication/login/MySqlSlickLoginAuthenticationDomain.scala
- toctoc/slickMySql/src/main/scala/io.buildo.toctoc/slick/authentication/token/MySqlSlickAccessTokenAuthenticationDomain.scala
- toctoc/slickMySql/src/test/scala/io.buildo.toctoc/slick/authentication/test/MySqlSlickLoginAuthenticationDomainFlowSpec.scala
- toctoc/slickPostgreSql/src/main/scala/io.buildo.toctoc/slick/authentication/login/PostgreSqlSlickLoginAuthenticationDomain.scala
- toctoc/slickPostgreSql/src/main/scala/io.buildo.toctoc/slick/authentication/token/PostgreSqlSlickAccessTokenAuthenticationDomain.scala
- toctoc/slickPostgreSql/src/test/scala/io.buildo.toctoc/slick/authentication/test/PostgreSqlSlickLoginAuthenticationDomainFlowSpec.scala
Closes #8
- shell scripts for running local postgres and mysql images
- new constructor argument `tableName` to customize table names.
Existing tests ✅
> #8: Provide PasswordResetAuthenticationDomain (closes #8)

- toctoc/core/src/test/scala/io.buildo.toctoc/core/authentication/InMemoryAuthenticationDomain.scala
Closes #17
In memory test double for supporting flow testing.
⚠️ Untested code, use with care.
See https://github.com/buildo/backend/issues/28
> #17: toctoc testing helper module (closes #17)

- toctoc/slickMySql/src/main/scala/io.buildo.toctoc/slick/authentication/login/MySqlSlickLoginAuthenticationDomain.scala
- toctoc/slickMySql/src/main/scala/io.buildo.toctoc/slick/authentication/token/MySqlSlickAccessTokenAuthenticationDomain.scala
- toctoc/slickPostgreSql/src/main/scala/io.buildo.toctoc/slick/authentication/login/PostgreSqlSlickLoginAuthenticationDomain.scala
- toctoc/slickPostgreSql/src/main/scala/io.buildo.toctoc/slick/authentication/token/PostgreSqlSlickAccessTokenAuthenticationDomain.scala
- toctoc/slickPostgreSql/src/test/scala/io.buildo.toctoc/slick/authentication/test/PostgreSqlSlickLoginAuthenticationDomainFlowSpec.scala
Closes #9
Modified current tests by explicitly specifying the `public` schema.
> #9: Explicitly use a configurable schema name for slick tables (closes #9)

- metarpheus/core/src/main/scala/io.buildo.metarpheus/core/Metarpheus.scala
Closes #38
`PlatformFileIO` now has a method `listAllFilesRecursively`, so I guess we can just use that instead of `listFiles` + recursion?
I've run it on a project by swapping the newly-compiled `index.js` file for the one in `node_modules` to check it finds the same files.
> #38: Revise implementation of recursivelyListFiles (closes #38)

- tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
Closes #69
It looks like `.distinct` doesn't work on `List[Term.Param]`. `.distinct` is now performed on `List[String]`  before conversion.
Tested locally.
> #69: Remove duplicate implicit codecs generated by tapiro (closes #69)

- tapiro/core/src/main/scala/io/buildo/tapiro/Cli.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
Closes #74
I've changed code generation to replace the use of `typeName` (which gets the name of a Metarpheus type) with a new function `toScalametaType` which instead converts the type back into a Scalameta type. This means that we get parametric types in endpoint types and JSON codecs.
For instance, before this we had:
val read: Endpoint[Id, BotReadError, BotSummary, Nothing]
...
id: JsonCodec[Id],
...
.out(jsonBody[Id])
and now:
val read: Endpoint[Id[Bot], BotReadError, BotSummary, Nothing]
...
id: JsonCodec[Id[Bot]],
...
.out(jsonBody[Id[Bot]])
Continued testing on our internal project, this fixes some compilation errors.
> #74: Fix parametric types and json codecs names (closes #74)

- tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
Closes #73
tested locally, the problem was there also for query parameters
> #73: Fix tapiro JsonCodec for post body (closes #73)

- tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
> #88: Errors should have proper json encoder instead of string (closes #88)

- tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
> #86: Get requests with no query parameters should not have `.tupled` (closes #86)

- tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/MetarpheusHelper.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
Closes #93 #82 
We now generate correct types for tagged union members in JSON codecs.
In the implicits I'm not generating the parameter for the codec for the sealed trait (because we're not using it currently) but only those for the case classes and objects that extend it.
Closes also #82 because name generation was getting a little bit more complicated, so I've already switched to dummy names `codec0`, `codec1`, ...
Tested on an internal project, fixes those compilation errors.
> #93: Tapiro sealed traits json codecs compilation error (closes #93 #82)

- tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
Closes #96
This is more a proposal rather than a pr. I ended up here just following types.
I'm forcing the controller to be something like (AuthToken is usually a string):
```scala
trait Controller[F[_], AuthToken] {
@query
def ghetto(
at: AuthToken,
): F[Either[Errore, SpittyCash]]
}
```
The generate code looks like this:
```scala
...
object ControllerHttp4sEndpoints {
def routes[F[_]: Sync, AuthToken](controller: Controller[F, AuthToken])(
implicit codec0: JsonCodec[SpittyCash],
codec1: JsonCodec[Errore.Errorone],
codec2: JsonCodec[Errore.Errorino],
codec3: PlainCodec[AuthToken],
cs: ContextShift[F]
): HttpRoutes[F] = {
val endpoints = ControllerEndpoints.create[AuthToken]()
val ghetto = endpoints.ghetto.toRoutes(controller.ghetto)
NonEmptyList(ghetto, List()).reduceK
}
}
```
```scala …
```
> #96: Add tapiro authentication (closes #96)

- metarpheus/core/src/main/scala/io.buildo.metarpheus/core/Metarpheus.scala
- metarpheus/core/src/main/scala/io.buildo.metarpheus/core/config.scala
- metarpheus/core/src/main/scala/io.buildo.metarpheus/core/intermediate/intermediate.scala
- metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ApiSuite.scala
- metarpheus/jsFacade/src/main/scala/io.buildo.metarpheus/core/JSFacade.scala
Closes #108
Added a config key to discard route error models. By default, it is false, that is, we do not discard them. If true, models that appear in route error types are not considered as being in use.
I've added a test to check that the model is discarded.
> #108: Allow discarding route error models via config (closes #108)

- metarpheus/jsFacade/npm/README.md
- metarpheus/jsFacade/npm/package.json
Version increase + README update for the metarpheus NPM package
The last released version was 2.0.0 (though the version increase had not been pushed).
This is a minor release since it adds an additional optional configuration key.
(I've already created the release on NPM.)
> metarpheus NPM release 2.1.0

- tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
Related to https://github.com/buildo/retro/issues/180
/cc @calippo
> Remove tapir endpoint output's need of string codecs

- tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/MetarpheusHelper.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
- tapiro/core/src/test/scala/io/buildo/tapiro/TapiroSuite.scala
- tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/test
Closes #203
- Implement wrapping for POST
- Fix GET routes without parameters
- Also revert 0a856a8 to fix encoding of `String` output (see https://github.com/buildo/retro/issues/180#issuecomment-604483453 and later comments)
- Introduce an enumerated type for route method (GET vs POST)
Notes:
- The wrapper classes are generated in the tapir endpoints file.
- To ensure that they have instances for `JsonCodec`, I've added an import of `import sttp.tapir.json.circe._` to that file (so it can generate `JsonCodec` instances given Circe `Encoder` and `Decoder`) and added the Circe semiauto derivation of the `Encoder` and `Decoder`, adding implicit parameters of `Encoder` and `Decoder` for field names.
- Not very nice: in the implicits we're now mixing tapir `JsonCodec`/`PlainCodec` with circe …
> #203: Wrap POST body as in wiro (closes #203)

- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
The import list is manipulated as a set. Let's sort it before printing
> Make imports in generated files predictable

- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
- tapiro/core/src/test/scala/io/buildo/tapiro/TapiroSuite.scala
Closes #349
The PR moves the `*RequestPayload` classes generated for commands inside the `*TapirEndpoints` object. This ensures that classes used in distinct endpoints do not clash if they have the same name (i.e. if the commands have the same name).
Note that this might be breaking: if a project references these classes (e.g. to use the endpoints as client and not only as server), the imports or qualified names should be updated.
Updated the automatic tests.
Tested on two internal projects, including the one which exhibited the bug because two controllers had a `create` command.
> #349: Tapiro generation bug when there are duplicate names for commands in different controllers

- ci/pipeline.yml
- mailo/src/main/scala/mailo/http/MailClient.scala
- mailo/src/main/scala/mailo/http/MailgunClient.scala
- mailo/src/main/scala/mailo/http/SMTPClient.scala
- mailo/src/main/scala/mailo/http/SendinblueClient.scala
Jakarta Mail 2.0.0 moved the package namespace from `javax.mail` to `jakarta.mail`, which currently leads to a failing build.
> Move Jakarta Mail namespace from javax to jakarta as per Jakarta 2.x

- docs/tapiro/introduction.md
- docs/tapiro/migrate.md
Fix two compile errors due to updated tapir version changing the `Codec` type.
> Fix compile errors in docs due to updated tapir

- ci/docs.yml
- ci/pipeline.yml
A bunch of small improvements / cleanups / optimizations to the CI pipeline:
* explicitly build docs on master and PRs;
* `on_success` and `on_failure` at job level for PRs;
* slack notifications for failures on master and successful releases;
* webhooks for Git and PR resources;
* a few other optimizations.
> CI pipeline improvements

- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
Post params of type Option[T] were handled as params of type T in RequestPayload class.
> support option in post

- build.sbt
- ci/docs.yml
- ci/pipeline.yml
- ci/release.yml
- enumero/ci/test.yml
- javaTimeCirceCodecs/ci/test.yml
- mailo/ci/test.yml
- metarpheus/ci/test.yml
- sbt-buildo/ci/compile.yml
- tapiro/ci/test.yml
- toctoc/ci/docker-compose.yml
- wiro/ci/test.yml
Currently the docs and release CI tasks are broken because they're looking for the tag 8u282_1.5.4_2.13.5 of hseeberger/scala-sbt which doesn't exist.
The PR updates to Scala 2.13.6 and updates CI images.
> Upgrade to Scala 2.13.6 and fix CI release

- metarpheus/core/src/main/scala/io.buildo.metarpheus/core/extractors/package.scala
- tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
- tapiro/core/src/test/scala/io/buildo/tapiro/TapiroSuite.scala
Closes #425
Generate endpoints as `lazy val` instead of `val` to prevent 'method too large' errors when compiling them.
Updated test + manual test on an internal project, where it solves the error.
> Fix 'method too large' compile error in tapiro endpoints

- sbt-buildo/src/main/scala/buildo/ScalaSettingPlugin.scala
Update kind-project to version 0.13.2 to support Scala 2.13.10 (version 0.13.1 is not published for 2.13.10)
> sbt-buildo: Update kind-projector to support Scala 2.13.10

- mailo/src/test/scala/mailo/SendinblueSpec.scala
Sendinblue now returns a different error message for invalid sender, see failed CI build https://concourse.our.buildo.io/builds/10748699
> mailo: change expected error from Sendinblue

- ci/pipeline.yml
- toctoc/ci/test.yml
This PR solves the issues with our pull-through cache not being able to retrieve postgres:16.1-alpine and mysql:8:
* the issue arises with images published as OCI images
* the docker-image resource performs a HEAD request for manifests but it does not support OCI images, thus lacking the media type "application/vnd.oci.image.index.v1+json" in the request's `Accept` header
* the pull-through cache is probably overly strict and [returns a 404](https://github.com/distribution/distribution/blob/v2.8.1/registry/handlers/manifests.go#L176C14-L176C14) (relevant log excerpt: `level=error msg="response completed with error" err.code="manifest unknown" err.message="OCI index found, but accept header does not support OCI indexes" go.version=go1.17.3`)
The use of registry-image instead of …
> Use registry-image instead of docker-image

- build.sbt
This PR updates the scala 3 version that is used by the monorepo to `3.3.1`. This should solve the problems that made [this CI build](https://concourse.our.buildo.io/builds/16056763) fail.
:white_check_mark: Launching crossCompilation with `+ compile` in sbt works fine now (it wasn't previously)
> Use scala 3.3.1

- project/Dependencies.scala
This PR updates `pureconfig` to 0.17.4, which is currently the latest version.
This is needed in projects that use both `wiro` and `pureconfig`, as mixing different versions of `pureconfig` can cause runtime errors.
> Update pureconfig to 0.17.4

- sbt-buildo/src/main/scala/buildo/ScalaSettingPlugin.scala
Update kind-project to version 0.13.3 to support Scala 2.13.14 (version 0.13.2 is not published for 2.13.14)
> sbt-buildo: Update kind-projector to support Scala 2.13.14
