buildo/retro

toctoc/core/src/main/scala/io.buildo.toctoc/core/authentication/AuthenticationDomain.scala
toctoc/core/src/main/scala/io.buildo.toctoc/core/authentication/Credential.scala
toctoc/core/src/main/scala/io.buildo.toctoc/core/authentication/TokenBasedAuthentication.scala
toctoc/core/src/main/scala/io.buildo.toctoc/core/authentication/token/Token.scala

#4: Remove Credential marker trait (closes #4)

---

sbt-buildo/src/main/scala/buildo/AssemblySettingPlugin.scala

#30: Discard module-info.class files in sbt-assembly (closes #30)

---

build.sbt
project/plugins.sbt

Waiting for the release to sync on Maven Central

Upgrade to sbt-buildo v0.11.0

---

build.sbt
docs/toctoc/installation.md
project/Dependencies.scala
toctoc/circe/src/main/scala/io/buildo/toctoc/circe/CirceSupport.scala
toctoc/circe/src/main/scala/io/buildo/toctoc/circe/package.scala
toctoc/circe/src/test/scala/io/buildo/toctoc/circe/CirceSupportSpec.scala

#11: Support circe semi auto derivation (closes #11)

---

toctoc/slickMySql/src/main/scala/io.buildo.toctoc/slick/authentication/token/MySqlSlickAccessTokenAuthenticationDomain.scala
toctoc/slickMySql/src/main/scala/io.buildo.toctoc/slick/authentication/token/MySqlSlickHelper.scala

#53: Convert Instant to Timestamp in MySQL (closes #53)

---

build.sbt
tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala

Closes #46
tested on testo project

#46: [Ready To Test]  Collect endpoints automatically (closes #46)

---

tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/MetarpheusHelper.scala
tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala

- First commit is the logic
- Secondo commit is just refactoring of modules
tested locally on `testo` project

Add error handling

---

project/Dependencies.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Cli.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/MetarpheusHelper.scala
tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
tapiro/sbt-tapiro/src/main/scala/io/buildo/tapiro/SbtTapiro.scala

#72: Fix tapiro main package (closes #72)

---

tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/build.sbt

Closes #75
- Tested locally
I know it can be improved, but I'm a little lazy

#75: Fix tapiro import packages (closes #75)

---

tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala

#85: Missing `PlainCodec` for query parameters (closes #85)

---

project/Dependencies.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala

#94: Update tapir tapiro to 0.12.15 (closes #94)

---

tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala

Closes #100
tested locally on dummy project

#100: Remove .tupled when controller has just 1 argument (closes #100)

---

.jvmopts
metarpheus/jsFacade/npm/package.json

#104: metarpheus release (closes #104)

---

tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala

#103: Add auth to tapiro akka-http (closes #103)

---

tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala

#110: Add tupled also to post requests in tapiro (closes #110)

---

tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala

#112: Remove unused imports in akkahttp generated code by tapiro (closes #112)

---

tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala

#115: When output is Unit remove .out(jsonBody[Unit]) (closes #115)

---

tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala

#154: Fix tapiro equality error (closes #154)

---

project/Dependencies.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
tapiro/sbt-tapiro/src/main/scala/io/buildo/tapiro/SbtTapiro.scala
tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/build.sbt

#160: Remove cats dependency from SBT plugin (closes #160)

---

project/Dependencies.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
tapiro/sbt-tapiro/src/main/scala/io/buildo/tapiro/SbtTapiro.scala

Closes #162
Tested locally
Working
Not working

#162: Use sbt logging instead of logback (closes #162)

---

tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala

#114: Fix path prefix in both akka-http and http4s (closes #114)

---

tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala

#172: Tapiro should not generate errorOut if `Unit` return type is used for errors (closes #172)

---

tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala

Allow tapiro users to provide `statusCodes`

---

tapiro/ci/test.sh
tapiro/ci/test.yml

#208: Tapiro CI fails because of missing curl (closes #208)

---

metarpheus/core/src/main/scala/io.buildo.metarpheus/core/extractors/controller.scala
metarpheus/core/src/main/scala/io.buildo.metarpheus/core/extractors/model.scala
metarpheus/core/src/main/scala/io.buildo.metarpheus/core/extractors/package.scala
metarpheus/core/src/main/scala/io.buildo.metarpheus/core/intermediate/intermediate.scala
metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ApiSuite.scala
metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ControllerSuite.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala

Closes #171
- add a new field in the `Route` model for the package of the controller
- import these packages in tapiro `HttpEndpoints`
Tested on an example project

#171: Tapiro doesn't know the package of the controller (closes #171)

---

tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
tapiro/core/src/test/scala/io/buildo/tapiro/TapiroSuite.scala

L'idea è far si che tapiro prenda il tipo dei token dal type parameter del controller.
In questo modo basterà chiamare il tipo Auth per far funzionare metarpheus.

make tapiro use type parameter for Auth
